### ISSUE TITLE
Documented toolchain does not have Verilator

### ISSUE THREAD

**Issue by kenta2** [bluespec/mcu-release#6]
After the fix to https://github.com/bluespec/mcu-release/issues/5 , now the documented toolchain does not contain Verilator, but the demo instructions use Verilator.

Users will probably have to build a recent version of verilator from source: https://github.com/verilator/verilator

The version of verilator packaged in Debian Buster does NOT work; it is too old.

**Comment by nirajnsharma** [comment]
Have pointed users to verilator source
